name: Prettier on pull requests

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository's previous and current states"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: false
      
      - name: "Run prettier on the changed files"
        uses: creyD/prettier_action@v4.3  # https://github.com/creyD/prettier_action/blob/v4.3/entrypoint.sh
        with:
          prettier_options: >-
            --write
            **/*.{js,jsx}
          only_changed: true
